# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "Nextcloud Social"
SPDX-PackageSupplier = "Nextcloud <https://nextcloud.com/contact/>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/social"

[[annotations]]
path = "l10n/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nextcloud translators"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "img/nextcloud.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud GmbH"
SPDX-License-Identifier = "LicenseRef-NextcloudTrademarks"

[[annotations]]
path = ["img/add_user.svg", "img/boost.svg", "img/emoji.svg", "img/favicon.ico", "img/notifications.svg", "img/reply.svg", "img/social-dark.svg", "img/social-promo.png", "img/social.svg", "img/social_dark.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2024 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "img/undraw/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Katerina Limpitsouni"
SPDX-License-Identifier = "AGPL-3.0-or-later"
SPDX-FileComment = "The undraw illustrations are released with a non-free license and thus not AGPL-compatible but we have the illustrators permissions to use these 8 images in this project. See https://github.com/nextcloud/social/issues/277#issuecomment-508480655 and below."
